# Generated by Django 4.2.6 on 2023-10-21 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "userAPI",
            "0002_remove_userprofile_date_joined_userprofile_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
