# Generated by Django 4.2.6 on 2023-10-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAPI", "0004_alter_userprofile_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="default-password", max_length=128),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(
                default="default-username", max_length=255, unique=True
            ),
        ),
    ]
